PREFIX cordis:  <http://cordis.europa.eu/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX obo:     <http://purl.obolibrary.org/obo/>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vitro:    <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>



CONSTRUCT {

    ?proj vivo:relates ?org .
    ?proj vivo:relates _:role .
    
    _:role a vivo:AdministratorRole . 
    _:role obo:RO_0000052 ?org .
    _:role obo:BFO_0000054 ?proj .
    
    ?org vitro:position 0 .

} WHERE {

    ?proj a vivo:Project .
    ?proj cordis:relations ?rel .
    ?rel cordis:associations ?asc .
    ?asc cordis:organization ?org .
    
    ?org a foaf:Organization .
    ?org ingest:type "coordinator" .
}