PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cordis: <http://cordis.europa.eu/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>


CONSTRUCT {
	?y a vivo:Grant .
    ?y rdfs:label ?title .
    ?y vivo:description ?objective .
} WHERE {
	?x cordis:project ?y .
    ?y cordis:title ?title .
	OPTIONAL { ?y cordis:objective ?objective }
}