PREFIX acti:	<http://vivoweb.org/ontology/activity-insight#>
PREFIX obo:		<http://purl.obolibrary.org/obo/>
PREFIX foaf:	<http://xmlns.com/foaf/0.1/>
PREFIX rdfs:	<http://www.w3.org/2000/01/rdf-schema#>



CONSTRUCT {
	
	?org a foaf:Organization .
	?org rdfs:label ?title .
	
	?org obo:RO_0000053 ?role .
	# An organazation has (_53) a role
	
	?role a obo:ERO_0000224 .
	# That role is a _224 (funding) role
	
	?role obo:BFO_0000054 ?proj .
	# This role gets realised (_54) in the project
	
} WHERE {
	
	?project a acti:ImpactProject .
	?project acti:otherFedResearchFunding ?title .
	BIND(IRI(CONCAT(STR(?project), "-org")) AS ?org)
	BIND(IRI(CONCAT(STR(?project), "-org-role")) AS ?role)

}
