PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?person <http://purl.obolibrary.org/obo/RO_0000053> ?leaderRole .
    ?leaderRole <http://purl.obolibrary.org/obo/RO_0000052> ?person .
    ?leaderRole a vivo:LeaderRole .
    ?leaderRole vivo:roleContributesTo ?org .
    ?org vivo:contributingRole ?leaderRole .
} WHERE {
    BIND(IRI(CONCAT(STR(?org), "-leaderRole-", STRAFTER(STR(?person), "://"))) AS ?leaderRole)
    { ?person vivo:currentlyHeadOf ?org }
      UNION 
    { ?org vivo:currentlyHeadedBy ?person 
      FILTER NOT EXISTS { ?person vivo:currentlyHeadOf ?org }
    }
    FILTER NOT EXISTS {
        ?person <http://purl.obolibrary.org/obo/RO_0000053> ?leaderRoleNode .
        ?leaderRoleNode vivo:roleContributesTo ?org .
    }
}
