PREFIX vivo: <http://vivoweb.org/ontology/core#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

CONSTRUCT {
    ?person <http://purl.obolibrary.org/obo/RO_0000053> ?memberRole .
    ?memberRole <http://purl.obolibrary.org/obo/RO_0000052> ?person .
    ?memberRole a vivo:MemberRole .
    ?memberRole vivo:roleContributesTo ?org .
    ?org vivo:contributingRole ?memberRole .
} WHERE {
     BIND(IRI(CONCAT(STR(?person), "-memberRole-", STRAFTER(STR(?org), "://"))) AS ?memberRole)
     {  ?person vivo:currentMemberOf ?org }
       UNION 
     { ?org vivo:hasCurrentMember ?person 
       FILTER NOT EXISTS { ?person vivo:currentMemberOf ?org }
     }
     FILTER NOT EXISTS {
         ?person <http://purl.obolibrary.org/obo/RO_0000053> ?memberRoleNode .
         ?memberRoleNode vivo:roleContributesTo ?org .
     }
}
