PREFIX arg: <http://purl.obolibrary.org/obo/> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/> 
PREFIX v:   <http://www.w3.org/2006/vcard/ns#> 
PREFIX vivo: <http://vivoweb.org/ontology/core#> 

CONSTRUCT {
    ?vcard v:hasTelephone ?fax .
    ?fax a v:Telephone .
    ?fax a v:Fax.
    ?fax v:telephone ?faxNumber . 
} WHERE {
    ?s vivo:faxNumber ?faxNumber .
    ?s arg:ARG_2000028 ?vcard .
    BIND(IRI(CONCAT(STR(?vcard), "-fax-", REPLACE(?faxNumber, "\\W", ""))) AS ?fax)
    FILTER NOT EXISTS {
        ?vcard v:hasTelephone ?faxNode .
        ?faxNode a v:Fax .
    }
}
