PREFIX foaf:     <http://xmlns.com/foaf/0.1/>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

CONSTRUCT  {
    ?x <http://purl.obolibrary.org/obo/RO_0000056> ?y # participatesIn
} WHERE {
    ?x a foaf:Organization .
    ?x vivo:relatedBy ?rel .
    ?rel vivo:relates ?y .
    ?y a vivo:Project .
}
