PREFIX oaf:     <http://namespace.openaire.eu/oaf/>
PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX obo:     <http://purl.obolibrary.org/obo/>



CONSTRUCT {

    ?project a vivo:Project .
    ?project vivo:identifier ?project_id .
    ?project ingest:projectId ?project_id .

    ?grant a vivo:Grant .
    ?grant vivo:identifier ?project_id .
    ?grant vivo:fundingVehicleFor ?project .
    ?grant ingest:grantId ?project_id .

} WHERE {

    ?x oaf:project ?project .
    BIND(IRI(CONCAT(STR(?project), "-grant")) AS ?grant)

    OPTIONAL {
	# Not all projects are guaranteed to have an identifier.
		?project ingest:code ?project_id .
    }
}
