PREFIX oaf:     <http://namespace.openaire.eu/oaf/>
PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX obo:     <http://purl.obolibrary.org/obo/>



CONSTRUCT {

    ?project a vivo:Project .
    ?project vivo:identifier ?project_id .
    
    _:grant a vivo:Grant .
    _:grant vivo:identifier ?project_id .
    _:grant vivo:fundingVehicleFor ?project .

} WHERE {

    _:x oaf:project ?project .
    
    ?project ingest:code ?project_id .
}
