PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX obo:     <http://purl.obolibrary.org/obo/>



CONSTRUCT {

    ?project a vivo:Project .
    ?project vivo:identifier ?project_id .
    
    _:grant a vivo:Grant .
    _:grant vivo:identifier ?project_id .
    _:grant vivo:fundingVehicleFor ?project .

} WHERE {

#   With just the "ingest:code" we map also the projects that cannot be retrieved with the verb: projects
#   but we take them as related projects to the publications.
#   The "ingest:code" is used only for the project identifier, so, we are sure we take only actual projects.

    ?project ingest:code ?project_id .
}
