PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>



CONSTRUCT {

    ?proj rdfs:label ?title .

} WHERE {

    ?proj a vivo:Project .
    
    ?proj ingest:title ?title .
    
    ?proj ingest:acronym ?acronym .
    FILTER ( ?acronym = "" ) .
}
