PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vcard:   <http://www.w3.org/2006/vcard/ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX obo:		<http://purl.obolibrary.org/obo/>



CONSTRUCT {

	# entity "has contact info" 
    ?project obo:ARG_2000028 _:vcard .
    ?grant obo:ARG_2000028 _:vcard .
    
    _:vcard vcard:hasURL _:url .
    
    _:url a vcard:URL .
    _:url vcard:url ?project_url .
    _:url rdfs:label ?project_url_str .

} WHERE {

    ?project a vivo:Project .
    
    ?grant vivo:fundingVehicleFor ?project .
    
    ?project ingest:websiteurl ?project_url_str .
    
    BIND ( xsd:anyURI( ?project_url_str ) AS ?project_url )
}
