PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX bibo:    <http://purl.org/ontology/bibo/>



CONSTRUCT {

    ?proj vivo:supportedInformationResource ?doc .
    ?doc vivo:informationSourceSupportedBy ?proj .

} WHERE {

    ?pub a bibo:Document .
    
    ?pub ingest:rels ?rels .
    ?rels ingest:rel ?rel .
    ?rel ingest:to ?to .
    
    ?rel ingest:code ?projectId .
    
    ?proj a vivo:Project .
    ?proj vivo:identifier ?projectId .
    
    FILTER EXISTS { ?to ingest:class "isProducedBy" }
}
