PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>



CONSTRUCT {

    ?proj vivo:freetextKeyword ?keyword .
   
} WHERE {

    ?proj a vivo:Project .
    ?proj ingest:keywords ?keyword .
}
