PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX obo:     <http://purl.obolibrary.org/obo/>
PREFIX vcard:   <http://www.w3.org/2006/vcard/ns#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>



CONSTRUCT {

    # org "has contact info" 
    ?org obo:ARG_2000028 ?vcard .
    
    ?vcard a vcard:Organization .
    ?vcard vcard:hasAddress ?address .
    
    ?address vivo:Country ?org_country_name .
    
    ?vcard vcard:hasURL ?url .
    ?url a vcard:URL .
    ?url vcard:url ?org_url .
    ?url rdfs:label ?org_url_str .

} WHERE {

    ?project a vivo:Project .
    ?project ingest:rels ?rels .
    ?rels ingest:rel ?rel .
    
    ?rel ingest:country ?country .
    ?country ingest:classname ?org_country_name .
    
    ?rel ingest:websiteurl ?org_url_str .
    BIND ( xsd:anyURI( ?org_url_str ) AS ?org_url )
    
    ?org a foaf:Organization .

    BIND(IRI(CONCAT(STR(?org), "-vcard")) AS ?vcard)
    BIND(IRI(CONCAT(STR(?org), "-vcard-address")) AS ?address)
    BIND(IRI(CONCAT(STR(?org), "-vcard-url")) AS ?url)
}
