PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX bibo:    <http://purl.org/ontology/bibo/>
PREFIX obo:     <http://purl.obolibrary.org/obo/>



CONSTRUCT {

    ?pub a bibo:AcademicArticle .
    
# Also a JournalArticle.
    ?pub a obo:IAO_0000013 .

} WHERE {

    ?pub a bibo:Document .
    ?pub ingest:children ?child .
    ?child ingest:instance ?inst .
    ?inst ingest:instancetype ?type .
    ?type ingest:classname "Article" .
}
