PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>
PREFIX bibo:    <http://purl.org/ontology/bibo/>



CONSTRUCT {

    ?pub a vivo:ConferencePaper .

} WHERE {

    ?pub a bibo:Document .
    ?pub ingest:children ?child .
    ?child ingest:instance ?inst .
    ?inst ingest:instancetype ?type .
    ?type ingest:classname "Conference object" .
}
