PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bibo:    <http://purl.org/ontology/bibo/>
PREFIX vitro:   <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>



CONSTRUCT {
    
    ?journal a bibo:Journal .
    ?journal rdfs:label ?journalName .
    
    ?journal bibo:issn ?issn .
    ?journal bibo:eissn ?eissn .
    
    ?journal vivo:publicationVenueFor ?pub .
    ?pub vivo:hasPublicationVenue ?journal .
    
} WHERE {

    ?pub a bibo:Article .
    
    ?pub ingest:journal ?jrnl .
    ?jrnl vitro:value ?journalName .

    #BIND(IRI(CONCAT(STR(?pub), "-journal")) AS ?journal)
    BIND(IRI(CONCAT("https://wheatvivo.org/individual/openaire-journal-", REPLACE(STR(?journalName), "\\W+", "-"))) AS ?journal)
    
    OPTIONAL {
       ?journal ingest:issn ?issn .
        FILTER ( ?issn != "" ) .
    }
    OPTIONAL {
        ?journal ingest:eissn ?eissn .
        FILTER ( ?eissn != "" ) .
    }
}
