PREFIX ingest:  <http://ingest.mannlib.cornell.edu/generalizedXMLtoRDF/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>



CONSTRUCT {

   ?x vivo:freetextKeyword ?keyword .
   
} WHERE {

    ?x ingest:keywords ?keyword .
}
