PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX vivo:    <http://vivoweb.org/ontology/core#>



CONSTRUCT {

	?entity vivo:relates ?org .
	?org ?orgP ?orgO .
	?orgO ?orgPP ?prgOO .
	?orgOO ?orgPPP ?orgOOO .
	
	?entity vivo:relates ?role .
	?role ?roleP ?roleO .
	
} WHERE {

	?entity vivo:relates ?org .
	
	?org a foaf:Organization .
	?org ?orgP ?orgO .
	?orgO ?orgPP ?prgOO .
	?orgOO ?orgPPP ?orgOOO .
	
	# Here we add 2 lower-level triples ("?orgO..." and "?orgOO...") in order to retrieve the organization's vcards.
	# That is, because the individual sparql query for vcards, can only be used for high-level entities,
	# which are retrieved by our java code, as wheat-related.
	
	?entity vivo:relates ?role .

	FILTER NOT EXISTS { ?role a foaf:Organization }
	?role ?roleP ?roleO .
}
